services:
  backend:
    build: .
    container_name: raijai-backend
    ports:
      - "${RAIJAI_BACKEND_PORT:-8088}:8080"
    environment:
      - PG_DB_HOST=${PG_DB_HOST}
      - PG_DB_PORT=${PG_DB_PORT}
      - PG_DB_USER=${PG_DB_USER}
      - PG_DB_PASSWORD=${PG_DB_PASSWORD}
      - DB_PG_RAIJAI_DB_NAME=${DB_PG_RAIJAI_DB_NAME}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_RAIJAI_CLIENT_ID=${KEYCLOAK_RAIJAI_CLIENT_ID}
      - RAIJAI_BACKEND_PORT=${RAIJAI_BACKEND_PORT:-8088}
    restart: always
