basePath: /api/v1
definitions:
  handlers.PaymentRequest:
    properties:
      amount:
        type: number
    type: object
  models.ActionType:
    enum:
    - CREATE
    - UPDATE
    - DELETE
    - PAYMENT
    type: string
    x-enum-varnames:
    - ActionCreate
    - ActionUpdate
    - ActionDelete
    - ActionPayment
  models.Category:
    properties:
      color:
        type: string
      createdAt:
        type: string
      icon:
        type: string
      id:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/models.CategoryType'
    type: object
  models.CategoryType:
    enum:
    - INCOME
    - EXPENSE
    type: string
    x-enum-varnames:
    - CategoryTypeIncome
    - CategoryTypeExpense
  models.Debt:
    properties:
      autoDeduct:
        type: boolean
      createdAt:
        type: string
      dueDate:
        type: string
      id:
        type: string
      installmentPlan:
        $ref: '#/definitions/models.InstallmentPlan'
      isInstallment:
        type: boolean
      personName:
        type: string
      remainingAmount:
        type: number
      remark:
        type: string
      title:
        type: string
      totalAmount:
        type: number
      type:
        $ref: '#/definitions/models.DebtType'
      wallet:
        $ref: '#/definitions/models.Wallet'
      walletId:
        type: string
    type: object
  models.DebtType:
    enum:
    - LENT
    - BORROWED
    type: string
    x-enum-varnames:
    - DebtTypeLent
    - DebtTypeBorrowed
  models.HistoryLog:
    properties:
      action:
        $ref: '#/definitions/models.ActionType'
      changes:
        type: string
      details:
        type: string
      entityId:
        type: string
      entityType:
        type: string
      id:
        type: string
      newValue:
        type: string
      previousValue:
        type: string
      timestamp:
        type: string
    type: object
  models.InstallmentPlan:
    properties:
      interestRate:
        type: number
      monthlyAmount:
        type: number
      paidMonths:
        type: integer
      startDate:
        type: string
      totalMonths:
        type: integer
    type: object
  models.Transaction:
    properties:
      amount:
        type: number
      category:
        $ref: '#/definitions/models.Category'
      categoryId:
        type: string
      createdAt:
        type: string
      createdBy:
        $ref: '#/definitions/models.User'
      createdById:
        type: string
      date:
        type: string
      description:
        type: string
      id:
        type: string
      toWallet:
        $ref: '#/definitions/models.Wallet'
      toWalletId:
        type: string
      type:
        $ref: '#/definitions/models.TransactionType'
      wallet:
        $ref: '#/definitions/models.Wallet'
      walletId:
        type: string
    type: object
  models.TransactionType:
    enum:
    - INCOME
    - EXPENSE
    - TRANSFER
    type: string
    x-enum-varnames:
    - TransactionTypeIncome
    - TransactionTypeExpense
    - TransactionTypeTransfer
  models.User:
    properties:
      avatarUrl:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  models.Wallet:
    properties:
      balance:
        type: number
      color:
        type: string
      createdAt:
        type: string
      currency:
        type: string
      id:
        type: string
      name:
        type: string
      owner:
        $ref: '#/definitions/models.User'
      ownerId:
        type: string
      type:
        $ref: '#/definitions/models.WalletType'
    type: object
  models.WalletType:
    enum:
    - CASH
    - BANK
    - CREDIT_CARD
    type: string
    x-enum-varnames:
    - WalletTypeCash
    - WalletTypeBank
    - WalletTypeCreditCard
host: raijai-api.sutthiporn.dev
info:
  contact: {}
  description: RESTful API for RaiJai Application
  title: RaiJai API
  version: "1.0"
paths:
  /auth/me:
    get:
      description: Get profile of the currently logged-in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get current user profile
      tags:
      - auth
  /categories:
    get:
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Category'
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    delete:
      description: Delete a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a category
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Category'
      summary: Update a category
      tags:
      - categories
  /debts:
    get:
      description: Get all debts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Debt'
            type: array
      summary: Get all debts
      tags:
      - debts
    post:
      consumes:
      - application/json
      description: Create a new debt (Lent or Borrowed)
      parameters:
      - description: Debt Data
        in: body
        name: debt
        required: true
        schema:
          $ref: '#/definitions/models.Debt'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Debt'
      summary: Create a new debt record
      tags:
      - debts
  /debts/{id}:
    delete:
      description: Delete a debt by ID
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a debt
      tags:
      - debts
    put:
      consumes:
      - application/json
      description: Update a debt by ID
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: string
      - description: Debt Data
        in: body
        name: debt
        required: true
        schema:
          $ref: '#/definitions/models.Debt'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Debt'
      summary: Update a debt
      tags:
      - debts
  /debts/{id}/payment:
    post:
      consumes:
      - application/json
      description: Deduct amount from debt
      parameters:
      - description: Debt ID
        in: path
        name: id
        required: true
        type: string
      - description: Payment Amount
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/handlers.PaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Debt'
      summary: Make a payment for a debt
      tags:
      - debts
  /history:
    get:
      description: Get history logs, optionally filtered by entity
      parameters:
      - description: Filter by Entity ID
        in: query
        name: entity_id
        type: string
      - description: Filter by Entity Type
        in: query
        name: entity_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.HistoryLog'
            type: array
      summary: Get history logs
      tags:
      - history
  /transactions:
    get:
      description: Get all transactions
      parameters:
      - description: Filter by Wallet ID
        in: query
        name: wallet_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
      summary: Get all transactions
      tags:
      - transactions
    post:
      consumes:
      - application/json
      description: Create a new transaction (Income, Expense, Transfer)
      parameters:
      - description: Transaction Data
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
      summary: Create a new transaction
      tags:
      - transactions
  /transactions/{id}:
    delete:
      description: Delete a transaction by ID
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a transaction
      tags:
      - transactions
    put:
      consumes:
      - application/json
      description: Update a transaction by ID
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      - description: Transaction Data
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transaction'
      summary: Update a transaction
      tags:
      - transactions
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    get:
      description: Get user details
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get a user by ID
      tags:
      - users
  /wallets:
    get:
      description: Get all wallets specific to a user
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Wallet'
            type: array
      summary: Get all wallets by User ID
      tags:
      - wallets
    post:
      consumes:
      - application/json
      description: Create a new wallet
      parameters:
      - description: Wallet Data
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/models.Wallet'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Wallet'
      summary: Create a new wallet
      tags:
      - wallets
  /wallets/{id}:
    delete:
      description: Delete a wallet by ID
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a wallet
      tags:
      - wallets
    put:
      consumes:
      - application/json
      description: Update a wallet by ID
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: string
      - description: Wallet Data
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/models.Wallet'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Wallet'
      summary: Update a wallet
      tags:
      - wallets
schemes:
- https
swagger: "2.0"
